### ISSUE TITLE
feat: A second GlobalTag

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/API#160]
### Tell us about your concept

A second GlobalTag, which is smaller than the main GlobalTag, is below the normal GlobalTag, but is only available to promoters, partners and team members.
This would be another reason why GlobalTags should be supported (:

**Comment by RappyTV** [comment]
Maybe we will think about something like that in the future when we grow bigger but right now I don't really see the point of allowing players to set a second tag. Also it's would bloat the player tags a bit in my opinion.
