### ISSUE TITLE
feat: Customizable sizes of own GlobalTags

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/API#161]
### Tell us about your concept

From Promoter you can customize the size of the text of the GlobalTag, there are 3 units, unit 1 is small, unit 2 normal, unit 3 a little larger than normal.

**Comment by RappyTV** [comment]
We don't plan on implementing something like this to prevent players from abusing such systems by making their tag extra long with spam and.then choosing the biggest size. I myself think that it's better to keep it a client-side setting.
