### ISSUE TITLE
feat: All GlobalTags export and import settings

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/API#162]
### Tell us about your concept

All GlobalTags export and import settings can be made ingame, within a code.

Example:
Each user has his own code, this is only visible when the player clicks on a button to display the code, if this code is copied, you can simply send it to your cell phone via Whatsapp or something like that, and send it to the laptop, if you enter the code there in the GlobalTags addon, the settings are adopted, i.e. all settings are adopted, as well as the GlobalTag that is entered. If the account on the laptop is also connected to Discord and is at least a promoter, the icon will also be adopted. What is also possible is that you could set when redeeming the code whether your own icon should also be adopted and whether the GlobalTag should also be adopted.

**Comment by RappyTV** [comment]
Well account related settings (like the tag, position and icon) are always synced anyways. I think it would be a lot of unnecessary effort to implement synchronization for the 3 client-side config options. I think that would be a better fit for an addon which syncs all LabyMod core/addon configs which I'm planning on writing.
